### ISSUE TITLE
Not working with REVB boards

### ISSUE THREAD

**Issue by simonwittber** [Blackaddr/BALibrary#20]
BAHardware.cpp line 133 needs to move up one line. :-)

**Comment by smnwttbr** [comment]
Apologies, line 113. 🤦

**Comment by Blackaddr** [comment]
@smnwttbr Good eye! Fixed in this commit:
https://github.com/Blackaddr/BALibrary/commit/5830973dc3a8cd0136b80a69b2c5dc024a9e6693

Thanks for your feedback!
