### ISSUE TITLE
FFT INIT FAILED when activating PitchShiftExpansion

### ISSUE THREAD

**Issue by crosswick** [Blackaddr/BALibrary#21]
Hi,

I'm getting the FFT INIT FAILED message on the serial monitor whenever I press the bypass button. Any idea why this may be?

I've tried on Windows 10 with the exact same setup as mentioned in the readme: Arduino 1.8.5 and Teensyduino 1.4.1. On MacOS I used Arduino 1.8.10 and Teensyduino 1.49 to the same effect.

Perhaps it's a CMSIS-DSP thing that needs to be configured? I get no errors or warnings during compilation.

My Teensy is a 3.6 and I've got a Blackaddr Teensy Guitar Rev. B board with a Rev. 2 Expansion Board.

Thanks in advance.

**Comment by Blackaddr** [comment]
PitchShiftExpansion was part of a pitch shifter I was playing with on a feature branch. Unfortunately I've not touched it in 5 years and didn't get the pitch shifter working (hence not merged into master branch). I will likely delete the branch eventually.

**Comment by crosswick** [comment]
I see, thank you for the clarification.
